### ISSUE TITLE
Incorrect indentation in code block which is a child of list item

### ISSUE THREAD

**Issue by alexanderlukanin13** [nicoulaj/idea-markdown#124]
Following code has incorrect preview:

```
3. Allow connection via user/password:

    - Add following lines in `/var/lib/pgsql/data/pg_hba.conf`

            local tickets test         trust
            host  tickets 127.0.0.1/32 trust
```

![1](https://f.cloud.github.com/assets/4417580/1370467/6fed7502-3a20-11e3-962d-4cd6bca63087.png)

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).

**Comment by alexanderlukanin13** [comment]
I guess this is no more relevant :-)
