### ISSUE TITLE
When quickdoc is enabled in IDE, quickdock dialog pops up continuously

### ISSUE THREAD

**Issue by nikmartin** [nicoulaj/idea-markdown#131]
I have my QuickDoc box set to popup at around 250 ms.  This works fine in most files, but with markdown plugin enabled, when editing a markdown file, the quickdoc box pops up EVERYWHERE my cursor is at the moment, making editing impossible. This happens in AndroidStudio, and Webstorm

**Comment by Guilouf** [comment]
It appen also for me, with pycharm community edition 5.0.3. Very anoying.
