### ISSUE TITLE
Markdown files should ignore "Strip trailing spaces on save"

### ISSUE THREAD

**Issue by kimu** [nicoulaj/idea-markdown#138]
There is a "Strip trailing spaces on save" setting in Preferences->editor->others in PHPStorm 7.1.

I have set it up to "strip all trailing spaces on save", as this is the default condition I need for all the file types I work with, except for Markdown files.

Markdown uses 4 spaces to indicate a new line and being part of the language itself, the plugin should ignore any setting related to trailing spaces, or at least applies that filter only after the fourth space.

**Comment by borisdiakur** [comment]
Using an .editorconfig file works for me.

```
[*.{md,markdown}]
trim_trailing_whitespace = false
```

Thanks @denofevil

**Comment by paven** [comment]
This should be default beahvoure not a config i have to take with me to every computer and every project.

**Comment by felipsmartins** [comment]
Installing PHPStorm EditorConfig plugin worked for me! :)

```
 [*.md]
trim_trailing_whitespace = false
```

**Comment by NabiKAZ** [comment]
@borisdiakur About `.editorconfig` config file, This works, But seems must install `EditorConfig`  plugin on `phpstorm` before it, as @felipsmartins said.
