### ISSUE TITLE
randomly freezes webstorm when opening markdown files 

### ISSUE THREAD

**Issue by dylang** [nicoulaj/idea-markdown#139]
I've never tried debugging a plugin - is there somewhere I should look for some debug output to make this ticket more useful?

**Comment by syzer** [comment]
+1

**Comment by GrayedFox** [comment]
This consistently happens to me, even now - request to re-open. Behaviour is slightly different - WebStorm (latest, on Mac 10.12.3) - will always hang when opening a .MD file the first time. After force quitting, I can open the file, so long as it's the first file I open when I open the editor new again (and not a different MD file). There are no embedded links, although there was an interesting character ----> ⚠️  <----that one - which I've now removed. Maybe unicode related?

Ah... no. Hang indefinitely again even without the character. Consistently hanging if I open the .MD file - although it won't hang if the last thing that happened was force quitting the IDE from trying to open it last time. Strange

**Comment by jouniso** [comment]
+1

**Comment by grantlittle** [comment]
+1

**Comment by jpcaparas** [comment]
+1 This is a pain 😞

I just marked the file as plain text so I don't encounter any more freezes.

**Comment by shawngo** [comment]
Going to have to +1 this too. Mac OS / Latest PHPStorm.

**Comment by olety** [comment]
+1 on Mac OS and PyCharm

**Comment by billwright** [comment]
+1 on Mac OS and latest IntelliJ

**Comment by gravitoni** [comment]
+1 on Windows 7 and latest PHP Storm

**Comment by naturtrunken** [comment]
+1 on macOS and RubyMine 2017.2.1. I'm since weeks afraid of md files... :-/

**Comment by gravitoni** [comment]
I find I can eliminate the problem by manually saving (CTRL+S) very frequently. By no means a solution but at least it averts the problem of PHP Storm hanging

**Comment by oleksii-lisovyi** [comment]
+1 on Ubuntu 16.04 LTS PHPStorm 2017.2.1 (latest version for now). Also tested on 2017.2 - there is this issue as well.

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
