### ISSUE TITLE
Rendering artifact of preview

### ISSUE THREAD

**Issue by MrElectroNick** [nicoulaj/idea-markdown#160]
![screenshot from 2014-05-31 17 30 48](https://cloud.githubusercontent.com/assets/3267843/3139220/31700858-e8d0-11e3-8a4f-858a3c54454b.png)

Blue line of tabs control is scrolled along with preview

Ubuntu 12.04 + Cinnamon 2 + PyCharm 3.4 + markdown 0.9.5

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
