### ISSUE TITLE
TODO items in .md files do not appear in TODO tool window

### ISSUE THREAD

**Issue by riclima** [nicoulaj/idea-markdown#211]
Operating system: Windows 7 SP1

Happened on WebStorm 9.0.1 (build #WS-139.252), as well as on IntelliJ IDEA Community Edition 14.0.1 (build #IC-139.252).

Markdown plugin version was 0.9.7.

Steps to reproduce:
- Create a test.md file.
- Write "TODO Hello, world."
- Open TODO tool window.

In WebStorm, TODO tool window shows the file in the list, as well as an arrow indicating that there are items inside:
![capture](https://cloud.githubusercontent.com/assets/6548873/5115173/e569dba4-700c-11e4-9c68-534bff140c58.PNG)
However, clicking on the arrows results on the items not being shown:
![capture2](https://cloud.githubusercontent.com/assets/6548873/5115181/f4962448-700c-11e4-85e0-444245bd8be8.PNG)

In IntelliJ IDEA, the arrow does not show. The result is the following:
![capture3](https://cloud.githubusercontent.com/assets/6548873/5115209/21d780d2-700d-11e4-89e7-1bc80d207f4b.PNG)

**Comment by mathse** [comment]
Todo elements are also not highlighted in the editor

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
