### ISSUE TITLE
Preview tab doesn't display english characters correctly.

### ISSUE THREAD

**Issue by stepan-shumilin** [nicoulaj/idea-markdown#212]
I've created simple document, but preview doesn't display english text correctly, only russian (system encoding is windows-1251).
Could you please answer, how can I fix this?

```
# Test content
test

# Тест
тест
````

---
File encoding is UTF-8
Platform - Windows 7
IDEA 12

![markdown_problems_1](https://cloud.githubusercontent.com/assets/10047896/5263721/7988a792-7a45-11e4-84a3-57c025d359d3.png)
![markdown_problems_2](https://cloud.githubusercontent.com/assets/10047896/5263722/79944f66-7a45-11e4-9a3a-548bea955cbb.png)

**Comment by alex-borkun** [comment]
I have UTF-8 and also experiencing this issue.

**Comment by alex-borkun** [comment]
But it seems developers don't care )

**Comment by stepan-shumilin** [comment]
Hello, all.

I found that JetBrains has official plugin "Markdown support".
It works fine for me (idea 14), so, issue not actual.
