### ISSUE TITLE
Table is not correctly shown

### ISSUE THREAD

**Issue by dvapelnik** [nicoulaj/idea-markdown#216]
This content

Content from cell 1 | Content from cell 2
---- | ----
asdad | adasd 
adad | ad a d
Adasd | ad ad

```javascript
$.fancybox('Text placeholder', {
    autoDimensions: false,
    width: 700,
    height: $(window).height(),
    onComplete: function () {
        var teachersView = new LightBoxTeacherView({
            model: new LightBoxTeacherModel({
                allTeachers: new TeacherCollection(),
                pupil: requestPupil,
                units: units,
                showAll: false,
                currentSchoolId: currentSchoolId,
                mainFormView: that
            }),
            titles: titles
        });

        teachersView.setElement($('#fancybox-content').children().get(0));
        teachersView.render();
    }
});
```

```javascript
this.get('teachers').on('all', function (eventName) {
    that.trigger('change');
});
```
shown with plugin like this

![laptop_20141207__23 23 20](https://cloud.githubusercontent.com/assets/1562244/5332690/2989392e-7e68-11e4-9a18-adfe5d2e4e4c.png)

my software
![laptop_20141207__23 28 16](https://cloud.githubusercontent.com/assets/1562244/5332710/05b2b31c-7e69-11e4-945d-821d197f0045.png)

![laptop_20141207__23 33 09](https://cloud.githubusercontent.com/assets/1562244/5332728/73394d1a-7e69-11e4-84ff-6fb2a1bca044.png)

![laptop_20141207__23 35 49](https://cloud.githubusercontent.com/assets/1562244/5332733/de1a0b1a-7e69-11e4-86a6-03b1b54b94a0.png)

Is this correct behavior of plugin or bug?

**Comment by estaub** [comment]
+1 for the table support in preview

**Comment by SashaOv** [comment]
+1 for GFM table support

**Comment by davelaflam** [comment]
+1 for table support in preview

**Comment by KarelWintersky** [comment]
+1 for table support in preview

**Comment by devinrsmith** [comment]
+1

**Comment by davelaflam** [comment]
Looks like it is working correctly, just need to enable it.

In order for tables to appear:
- install plugin
- open preferences
- click the dropdown arrow for Other Settings
- click on Markdown within the Other Settings list
- click the checkbox next to Tables.
- click [ok] button to close preferences.

**Comment by devinrsmith** [comment]
That works, thanks.

**Comment by davelaflam** [comment]
@nicoulaj - could be worth updating the Readme with new screenshots/notes since the internals of the IDE has changed quite a bit lately?

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
