### ISSUE TITLE
The code quotes don`t rendered correct in the preview

### ISSUE THREAD

**Issue by markusguenther** [nicoulaj/idea-markdown#238]
Thanks for your markdown plugin. I really like markdown and used separate markdown apps before your plugin.

I maybe found a little issue with code quotes.

The following code does not work in a right way. The preview shows the quotes and has not the whole code marked as code quote.

```
# used in the single view template to render the news content
lib.mainContent < styles.content.col0

lib.pageTemplate {
	variables {
		CONTENT = COA
		CONTENT {
			# load the plugin instead of any page template content on news pages
			10 = COA
			10 {
				10 < tt_content.list.20.sgnews_singleview
				if.value.field = doktype
				if.equals = 116
			}

			# load the overview plugin on category pages
			20 = COA
			20 {
				10 < tt_content.list.20.sgnews_overview
				if.value.field = doktype
				if.equals = 117
			}
		}
	}
}
```

![bildschirmfoto 2015-07-29 um 10 14 15](https://cloud.githubusercontent.com/assets/1014126/8952868/1346b940-35db-11e5-93fc-35fd0b7f326e.png)

**Comment by ShyykoSerhiy** [comment]
It seams that it works just like expected
![issue](https://cloud.githubusercontent.com/assets/1106995/8979773/b35638e6-36b4-11e5-8847-2613e788f9ad.gif)

# used in the single view template to render the news content
lib.mainContent < styles.content.col0

lib.pageTemplate {
    variables {
        CONTENT = COA
        CONTENT {
            # load the plugin instead of any page template content on news pages
            10 = COA
            10 {
                10 < tt_content.list.20.sgnews_singleview
                if.value.field = doktype
                if.equals = 116
            }

            # load the overview plugin on category pages
            20 = COA
            20 {
                10 < tt_content.list.20.sgnews_overview
                if.value.field = doktype
                if.equals = 117
            }
        }
    }
}

**Comment by markusguenther** [comment]
Hmm ok thats strange... do i set something in the preferences?

**Comment by vsch** [comment]
Turn on the `Fenced code blocks` in settings / Other Settings / Mardown. Fenced code blocks are an extension to Markdown, by default all extensions are turned off.
