### ISSUE TITLE
Proper colors inheritance

### ISSUE THREAD

**Issue by nazar-pc** [nicoulaj/idea-markdown#243]
I have quite good [color theme](https://github.com/nazar-pc/CleverStyle-PhpStorm-theme) (screenshot is a bit old, but anyway) and I'd like to add markdown highlighing, but it doesn't inherit default values as specified in `General` and `Language defaults` in color settings.
Can you add proper inheritance so that I'll not need to add all colors manually? It would be much easier for me to maintain theme.

**Comment by vsch** [comment]
I don't think this plugin is beng maintained. I forked it about a month ago and gave it some TLC. It has been thoroughly overhauled. You can see it at <https://github.com/vsch/idea-multimarkdown> or you can download it on the [official plugin page](https://plugins.jetbrains.com/plugin?pr=&pluginId=7896).

**Comment by nazar-pc** [comment]
@vsch, thanks, looks like I found wrong repository, refilled as https://github.com/vsch/idea-multimarkdown/issues/8
