### ISSUE TITLE
Lost syntax highlighting IDEA CE 14.1.4

### ISSUE THREAD

**Issue by NeuroNex** [nicoulaj/idea-markdown#245]
While editing a md file, suddenly syntax highlighting stops working for new text. Closing the file and reopen then the entire file lost syntax highlight. Unsintall + reinstall plug in didn't help. Looks like the issue happen around midnight, Is there any time setting that makes the plug in disables itself on 2015-09-14?

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).

**Comment by NeuroNex** [comment]
Hi Nicolas,

Thanks for the info. The official markdown plugin was very bad before. But since IntelliJ IDEA version 2016.1 it works now perfectly well.
