### ISSUE TITLE
Text/Preview Options Missing in IntelliJ IDEA 15 EAP 

### ISSUE THREAD

**Issue by rbeaini** [nicoulaj/idea-markdown#248]
both text & preview panes appear side by side in IDEA 15 EAP.
selection tabs are no longer there.

**Comment by shuttie** [comment]
Installed plugin on latest EAP 143.249.6 and tabs are on their places:
![idea-md](https://cloud.githubusercontent.com/assets/999061/10640304/c9a02a04-781c-11e5-9148-158b6f831669.jpg)
@rbeaini what's wrong?

**Comment by rbeaini** [comment]
looks like getting the latest EAP solved this... thank you
