### ISSUE TITLE
Customize fonts

### ISSUE THREAD

**Issue by Ohar** [nicoulaj/idea-markdown#260]
Can someone add font customization feature?
Default font is awful and there is no way to change it or even make zoom.
![Default font is awful](http://puu.sh/ozWQO/c71164d3f1.png)
I would change it to Consolas for example, but now there is now way for it.

Thank you.

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).

**Comment by Ohar** [comment]
Oh, thank you.
