### ISSUE TITLE
Suppress trailing spaces stripping

### ISSUE THREAD

**Issue by vvavrychuk** [nicoulaj/idea-markdown#33]
Since trailing spaces are essential part of Markdown syntax this plugin should suppress trimming trailing spaces of Markdown files which is done by `TrailingSpacesStripper` class and configured by `combobox.strip.trailing.spaces.on.save`.

Frankly speaking I didn't found out how to do that without modifying IDEA source code.

Thanks

**Comment by cfactolerin** [comment]
It seems that the spaces are still being stripped if ever you save the file and your cursor is on a different line with trailing spaces.

Assume that the . are spaces
Example:
This is line 1..
This is line 2..
This is line 3..

If I save the the file and my cursor is on line 1, the trailing spaces on line 1 won't be stripped BUT line 2 and line 3 gets stripped.

If I save on line 4, all the trailing spaces will be stripped.

I am currently using IntelliJ 14.0.2 and Markdown 0.9.7
Thanks for the plugin :)

**Comment by sonarxavier** [comment]
same problem here...

**Comment by cgatesman** [comment]
I am seeing this problem, too.  You can only have at most one line with trailing blanks if you have `Strip trailing spaces on Save:` set to `All`.

**Comment by manurg** [comment]
same problem here. I'm on IntelliJ IDEA with plugin version 0.9.7.

**Comment by alexfdz** [comment]
+1 for 0.9.7 and IDEA 14.0.1

**Comment by borisdiakur** [comment]
In https://github.com/nicoulaj/idea-markdown/issues/138#issuecomment-42680755 @denofevil mentions that you can make use of the editorconfig plugin, which by now is a built in plugin. Here is what you would put into the .editorconfig file:

```
[*.{md,markdown}]
trim_trailing_whitespace = false
```
