### ISSUE TITLE
Java 6 support

### ISSUE THREAD

**Issue by OlegYch** [nicoulaj/idea-markdown#84]
Please compile the plugin with target 1.6 otherwise it's not usable with Java 6 (which is recommended for intellij).

**Comment by antivir88** [comment]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
[   2260]  ERROR -    #com.intellij.lang.Language - Language with ID 'Markdown' is already registered: class net.nicoulaj.idea.markdown.MarkdownLanguage

**Comment by Jwely** [comment]
+1

`[    986]  ERROR -    #com.intellij.lang.Language - Language with ID 'Markdown' is already registered: class com.vladsch.idea.multimarkdown.MarkdownLanguage 
java.lang.Throwable`
